### ISSUE TITLE
Reading stop and program freeze

### ISSUE THREAD

**Issue by jeffbzrr** [cthill/SNESDump#1]
On my setup, reading stop and program freeze in 32kb or 64kb.
I believe that because my setup is protoboard and my arduino is chinese (USB to serial is CH340).
I reduce the serial baudrate for 115200 and and everything works.

**Comment by cthill** [comment]
Hello! I did not have much success with high baud rates on cheap Arduino clones. Try swapping it for an Arduino board with a legitimate FTDI USB to serial chip. I used the Arduino Nano for my build.

Also, what operating system are you using?

**Comment by jeffbzrr** [comment]
Hi. I no have a legitimate arduino and its more expensive in my country.
But that's not a problem for me. Wanted to leave the warning to other people who have cheapest arduino.

I use Debian 9 x64.

Congratulations for the project.

**Comment by cthill** [comment]
Ahh I see. Thanks for the info! I will add it to the project documentation. And thanks for trying out the project!

**Comment by joaopauloap** [comment]
Oi Jefferson. Meu arduino nano também é com o  CH340. Você conseguiu executar esse projeto? Estou tendo problemas, até abri um tópico

**Comment by jeffbzrr** [comment]
Olá, @joaopauloap. Consegui executar sim, em uma protoboard. Deu bastante trabalho porque são muitas conexões pra dar errado. O problema que eu tive foi o de ler e gravar saves, mas ler a ROM correu tudo certo. Qualquer coisa fala aí, valeu.

**Comment by joaopauloap** [comment]
Meu principal objetivo é ler rom, ainda não testei o save. Aqui está acontecendo que os bytes estão se repetindo. Em jogos LoRom Quando chega no endereço 7FFF repete tudo desde o endereço 0, Ai quando chega no FFFF repete de novo. e nos HiRom isso acontece a partir do FFFF. Tem alguma ideia do que seja? ja chequei as conexões e parece estar tudo certo. Ele detecta o cabeçalho do cartucho, o nome, tamanho, tipo de rom, etc, tudo certo.. os bytes estão corretos até esse ponto onde começa a se repetirem

**Comment by jeffbzrr** [comment]
Pelo padrão que vc relata, me parece ser um mal contato nas conexões do bus de endereço, eu chutaria isso. Acredito pegando esses endereços onde começa a repetição dê pra talvez entender qual conexão seria.

**Comment by joaopauloap** [comment]
Oi Jefferson, obrigado. Fiz uma limpeza com alcool isopropilico e uma escova e funcionou, nem precisei resoldar nada (fiz nessas placas furadas universais, pensa no trabalho). Estou pensando aqui se dá pra modificar esse projeto para fazer a escrita nas eproms também, principalmente flash.

**Comment by jeffbzrr** [comment]
Que bom que deu certo. Uma época eu precisei de uma gravadora e daí eu fiz a partir do datasheet do chip que eu queria gravar, mas deve ter algo mais pronto se a gravadora foi o objetivo fim.
